"""cria a tabela pedidos

Revision ID: 1ddb97cc9d8e
Revises: 7c23566d1528
Create Date: 2026-01-30 10:21:03.017517

"""
from typing import Sequence, Union
from sqlalchemy_utils import ChoiceType
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ddb97cc9d8e'
down_revision: Union[str, Sequence[str], None] = '7c23566d1528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status',ChoiceType(choices=[
            ('PENDENTE', 'PENDENTE'),
            ('EM_PREPARO', 'EM_PREPARO'),
            ('ENVIADO', 'ENVIADO'),
            ('ENTREGUE', 'ENTREGUE'),
            ('CANCELADO', 'CANCELADO')]), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('itens', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('pedido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item_pedido')
    op.add_column('usuario', sa.Column('codigo_recuperacao', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('codigo_expiracao', sa.DateTime(), nullable=True))
    op.add_column('usuario', sa.Column('tentativas_codigo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'tentativas_codigo')
    op.drop_column('usuario', 'codigo_expiracao')
    op.drop_column('usuario', 'codigo_recuperacao')
    op.create_table('item_pedido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sabor', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pedido', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pedido_pkey'))
    )
    op.drop_table('itens_pedido')
    op.drop_table('user_token')
    op.drop_table('pedido')
    # ### end Alembic commands ###
