"""Initial Migration

Revision ID: 7c23566d1528
Revises: 
Create Date: 2025-11-18 15:25:38.118584

"""
from typing import Sequence, Union
from sqlalchemy_utils import ChoiceType
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c23566d1528'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('status',ChoiceType(choices=[
            ('PENDENTE', 'PENDENTE'),
            ('EM_PREPARO', 'EM_PREPARO'),
            ('ENVIADO', 'ENVIADO'),
            ('ENTREGUE', 'ENTREGUE'),
            ('CANCELADO', 'CANCELADO')]), nullable=True),
        sa.Column('usuario', sa.Integer(), nullable=True),
        sa.Column('preco', sa.Float(), nullable=False),
        sa.Column('itens', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('pedido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuario', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('usuario', sa.Column('ativo', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('usuario_email_key'), 'usuario', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('usuario_email_key'), 'usuario', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('usuario', 'ativo')
    op.drop_column('usuario', 'admin')
    op.drop_table('itens_pedido')
    op.drop_table('pedido')
    # ### end Alembic commands ###
