"""tabela de produtos criada

Revision ID: c4b94ffa8063
Revises: 1ddb97cc9d8e
Create Date: 2026-02-06 15:54:34.662531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b94ffa8063'
down_revision: Union[str, Sequence[str], None] = '1ddb97cc9d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sabor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('itens_pedido', 'sabor',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True,
               postgresql_using="sabor::integer"
               
               )
               
               # Se houver texto, ele tenta converter. 
               # Se for texto não numérico, vai dar erro.
               # Se quiser apenas zerar os dados para converter, use: 
               # postgresql_using="NULL::integer"
               
    op.create_foreign_key(None, 'itens_pedido', 'produto', ['sabor'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itens_pedido', type_='foreignkey')
    op.alter_column('itens_pedido', 'sabor',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_table('produto')
    # ### end Alembic commands ###
